<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/ryu/02_pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#파이썬, Numpy 자료구조 복습
#리스트:순서 0, 수정 가능, []
#튜플: 순서 0, 수정 불가능, ()
#딕셔너리:키&값 쌍, {}
#ndarray: 반복문 없이 배열 처리, 선형대수 관련 기능 제공

In [ ]:
#pandas 기본 자료구조(Numpy 기반)
#Series: 1차원 데이터를 위한 자료구조
#DataFrame: 2차원 데이터를 위한 자료구조

In [ ]:
#임포트 방식은 크게 두가지

#1)필요한 클래스만 불러오기 -> 모듈명 명시 필요 X
from pandas import Series, DataFrame
Series()
DataFrame()

#2)그냥 전체 다 불러오기(with 별칭)
import pandas as pd
pd.Series()
pd.DataFrame()

In [ ]:
#Series 객체 생성

import pandas as pd

arr = [0,1,2,3]
arr

[0, 1, 2, 3]

In [ ]:
s = pd.Series(arr) #arr라는 리스트를 인자값으로 하는 Series 객체를 s에 할당
s

0    0
1    1
2    2
3    3
dtype: int64

In [ ]:
type(s) #타입은 Series

pandas.core.series.Series

In [ ]:
#Series 내부 구조
#행 번호와 인덱스를 사용해 데이터 관리(접근)
#행 번호: 자동으로 부여됨(수정 불가) -> 별도로 보이는 것은 X
#인덱스: 문자/숫자로 설정 가능(default:0부터 시작하는 정수), 딕셔너리의 키와 유사 개념
#행 번호는 앞/마지막 값 가져올 때 편리 ex) [-1] -> 뒤에서 첫번째
#인덱스는 명시적인 경우 그 이름으로 값 가져올 때 편리 ex) '류희수'

In [ ]:
data = [100, 200, 300]
index = ['월', '화', '수']

s = pd.Series(data,index) #인덱스와 값을 가지고 Series 객체 생성
s

월    100
화    200
수    300
dtype: int64

In [ ]:
#Series 클래스의 속성
#index: 시리즈 객체의 인덱스에 접근 ex) (객체명).index
#values: 시리즈 객체의 값에 접근 ex) (객체명).values

In [ ]:
s.index

Index(['월', '화', '수'], dtype='object')

In [ ]:
s.values

array([100, 200, 300])

In [ ]:
s.array #value처럼 값을 반환

<NumpyExtensionArray>
[np.int64(100), np.int64(200), np.int64(300)]
Length: 3, dtype: int64

In [ ]:
#아이스크림 연습문제
#메로나:500, 누가바:800. 빠삐코:200

In [ ]:
import pandas as pd

data = [500, 800, 200]
index = ['메로나', '누가바', '빠삐코']
pd.Series(data,index)

메로나    500
누가바    800
빠삐코    200
dtype: int64

In [ ]:
type(s) #역시나 타입은 Series

pandas.core.series.Series

In [ ]:
s.index, s.values #이 둘은 메소드가 아니며, 속성값을 가져온다는 점을 주의

(Index(['월', '화', '수'], dtype='object'), array([100, 200, 300]))