<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/euitae-branch/03_%ED%8C%90%EB%8B%A4%EC%8A%A4_%EC%8B%9C%EB%A6%AC%EC%A6%88(Series)_%EC%9D%B8%EB%8D%B1%EC%8B%B1%EA%B3%BC_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = [100,200,300]
index = ["월", "화", "수"]
s = pd.Series(data, index)
print(s.iloc[0]) # 정수 위치
print(s.loc["월"])

100
100

In [ ]:
import pandas as pd

data = [100,200,300]
index =["월", "화", "수"]
s = pd.Series(data,index)

In [ ]:
# iloc [행번호] integer + location
# loc ["인덱스"] location

In [ ]:
s.loc["월"]

np.int64(100)

In [ ]:
s

월    100
화    200
수    300
dtype: int64

In [ ]:
s["월"]

np.int64(100)

In [ ]:
s[0]

/tmp/ipykernel_14098/243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

np.int64(100)

In [ ]:
print( s.iloc[0:2])

월    100
화    200
dtype: int64

In [ ]:
s.loc["화":"수"]

화    200
수    300
dtype: int64

In [ ]:
m = [1, 2, 3,4 ]

In [ ]:
m[0]

1

In [ ]:
m[[0,2]] # 0하고 2가져와라 안됨

TypeError: list indices must be integers or slices, not list

In [ ]:
s