<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/suyeon_branch/3_%ED%8C%90%EB%8B%A4%EC%8A%A4_%EC%8B%9C%EB%A6%AC%EC%A6%88_%EC%9D%B8%EB%8D%B1%EC%8B%B1_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#iloc 속성 이용: 행 번호를 통하여 인덱싱

import pandas as pd

data = [100, 200, 300]
index = ['월', '화', '수']

s = pd.Series(data, index)

s.iloc[0]
print(s)

np.int64(100)

In [4]:
#loc 속성 이용: 인덱스를 통하여 인덱싱

s.loc['화']

np.int64(200)

In [5]:
#대괄호 사용하여 인덱싱 (인덱스를 통하여 인덱싱)

s['월']


#대괄호 사용하여 인덱싱 (행번호를 통하여 인덱싱)
s[1]

/tmp/ipykernel_2898/2513736753.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

np.int64(200)

In [ ]:
#iloc 속성 이용: 행 번호 기반 슬라이싱

s.iloc[0:2]

월    100
화    200
dtype: int64

In [ ]:
#iloc 속성 이용: 인덱스 기반 슬라이싱
#끝 인덱스를 포함함 !!!!!!!!!

s.loc['화':'수']

화    200
수    300
dtype: int64

In [ ]:
#연속적이지 않은 여러 개의 값을 한 번에 인덱싱


#iloc 속성 이용
target = [0, 2] #가져오고 싶은 데이터의 행 번호를 쉼표로 연결하여 적음
s.iloc[target]
s.iloc[ [0, 2] ]

#loc 속성 이용
target = ['월', '수']
s.loc[target]
s.loc[ ['월', '수'] ]

월    100
수    300
dtype: int64