<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/euitae-branch/05%ED%8C%90%EB%8B%A4%EC%8A%A4_%EC%8B%9C%EB%A6%AC%EC%A6%88_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 브로드캐스팅: 연산이 전체 값에 적용
from pandas import Series # 판다스 라이브러리에서 시리즈라는 도구만
s = Series([100, 200, 300]) # 시리즈 객체를 만들고 s에 할
print(s+10)

0    110
1    210
2    310
dtype: int64

In [3]:
# 사칙연산
high = Series([51500, 51200, 52500, 51500, 51500])
low = Series([50700, 50500, 50500, 50800, 50700])
diff = high - low
print(diff)

0     800
1     700
2    2000
3     700
4     800
dtype: int64

In [7]:
high = Series(data= [51500, 51200, 52500], index= ["5/1","5/2", "5/3" ])
low = Series(data= [50700, 50500, 50500 ], index = ["5/1", "5/2", "5/4"])
diff = high - low
print(diff)

5/1    800.0
5/2    700.0
5/3      NaN
5/4      NaN
dtype: float64

In [8]:
# 시리즈 비교연산
s = Series(data= [100,200,300,400,500])
cond= s> 300
print(cond)

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [15]:
# 시리즈 필터링
from pandas import Series
s = Series(data= [100,200,300,400,500])
cond=[False,False,False,True,True]
s[cond]

3    400
4    500
dtype: int64

In [17]:
s = Series(data= [100,200,300,400,500])
cond= s> 300
print(s[cond])

3    400
4    500
dtype: int64

In [18]:
import pandas as pd
저가 = pd.Series([100,200,300,400,600])
고가 = pd.Series([100,300,400,500,600])

cond = (고가 - 저가) >= 100
고가[cond]

1    300
2    400
3    500
dtype: int64

In [21]:
data = [93000, 82400, 99100, 81000, 72300]
index = ['05/14', '05/15', '05/16', '05/17', '05/18']
종가 = pd.Series(data=data, index=index)
print(종가)

05/14    93000
05/15    82400
05/16    99100
05/17    81000
05/18    72300
dtype: int64

In [22]:
조건 = (종가 >= 80000) & (종가 <= 90000)
print(종가[조건])

05/15    82400
05/17    81000
dtype: int64

In [24]:
종가[조건].index

Index(['05/15', '05/17'], dtype='object')

In [25]:
for date in 종가[조건].index:
    print(date)

05/15
05/17