<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/euitae-branch/4%ED%8C%90%EB%8B%A4%EC%8A%A4%EC%8B%9C%EB%A6%AC%EC%A6%88_%EC%B6%94%EA%B0%80_%EC%82%AD%EC%A0%9C_%EC%88%98%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
data = [100, 200, 300]
index = ["월","화", "수" ]
s = pd.Series(data,index)

s.loc["목"] = 400
print(s)

월    100
화    200
수    300
목    400
dtype: int64

In [8]:
# 시리즈 삭제
# 원본 유지, 새로운 시리즈 객체 리턴

s1 = s.drop('월')
print(s1)
print(s)

화    200
수    300
목    400
dtype: int64
월    100
화    200
수    300
목    400
dtype: int64

In [9]:
# 시리즈 수정
s.iloc[0]
s.loc["수"] = 3000
s

월     100
화     200
수    3000
목     400
dtype: int64

In [10]:
import pandas as pd
data = [100,200,300]
index = ['월', '화', '수']
s = pd.Series(data = data, index = index)
s

월    100
화    200
수    300
dtype: int64

In [11]:
s['목'] = 400

In [12]:
s

월    100
화    200
수    300
목    400
dtype: int64

In [13]:
s.loc['금'] = 500
s

월    100
화    200
수    300
목    400
금    500
dtype: int64

In [14]:
s.drop('목')

월    100
화    200
수    300
금    500
dtype: int64

In [15]:
s

월    100
화    200
수    300
목    400
금    500
dtype: int64

In [16]:
s.drop('목', inplace = True) # 원본데이터 수정

In [17]:
s.drop(['수','금'])

월    100
화    200
dtype: int64

In [18]:
s

월    100
화    200
수    300
금    500
dtype: int64

In [20]:
s.drop('금', inplace= True)
s

월    100
화    200
수    300
dtype: int64

In [23]:
s['수'] = 3000
s

월     100
화     200
수    3000
dtype: int64

In [24]:
s.iloc[2] = 4000
s

월     100
화     200
수    4000
dtype: int64

In [25]:
s.loc['수'] = 5000
s

월     100
화     200
수    5000
dtype: int64