<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/euitae-branch/pandas_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 리스트: 순서O 수정O []
# 튜플: 순서O 수정X ()
# 딕셔너리: {key: value}
# Ndarray: 반복문 없이 선형대수 관련

In [13]:
# series: numpy 기반 1차원 데이터
# DataFrame: numpy 기반 2차원 데이터
# 임포트 방식
# from panda import Series, DataFrame
# import pandas as pd

In [14]:
from pandas import Series

arr = [0,1,2,3] # row 데이터 생성
s = Series(arr) # list -> Series 타입으로 변경
print(s)

0    0
1    1
2    2
3    3
dtype: int64

In [15]:
import pandas as pd

arr = [0,1,2,3 ]

In [16]:
type(arr)

list

In [17]:
s = pd.Series(arr)
s

0    0
1    1
2    2
3    3
dtype: int64

In [18]:
type(s)

pandas.core.series.Series

In [19]:
data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64

In [20]:
data = [100, 200, 300]
index = ["월", "화", "수"] # 행번호 0부터 딕셔너리 키 느낌
s = Series(data,index)
print(s)

월    100
화    200
수    300
dtype: int64

In [21]:
data = [100, 200, 300]
index = ["월", "화", "수"]

s = pd.Series(data, index)

In [22]:
s

월    100
화    200
수    300
dtype: int64

In [22]:
# Series 속성: class 내부 변수
# index
# values

In [23]:
s.index

Index(['월', '화', '수'], dtype='object')

In [24]:
s.values

array([100, 200, 300])

In [25]:
s.array #<NumpyExtensionArray>의 한 종류 (PandasArray)

<NumpyExtensionArray>
[np.int64(100), np.int64(200), np.int64(300)]
Length: 3, dtype: int64

In [29]:
# 연습문제
import pandas as pd

data = [500, 800, 200]
index = ["메로나","누가바", "빠삐코"]
s= pd.Series(data,index) # 시리즈 클래스의 객체를 만드는 코드,
# 생성된 객체를 s에 할당

In [28]:
s

메로나    500
누가바    800
빠삐코    200
dtype: int64